### ISSUE TITLE
Package hijacked? 

### ISSUE THREAD

**Issue by danielo515** [folktale/data.maybe#18]
Hello,
I just clicked on the npm link to the documentation and I have been sent to a fraudulent page. Are you aware of it?

**Comment by robotlolita** [comment]
Ah. It's been a few years since I'm not the owner of that domain anymore (in hindsight I should've kept it). 

The documentation for this version is here: https://folktalegithubio.readthedocs.io/en/latest/, the new documentation is here: https://folktale.origamitower.com/. Most places should be pointing to the new links, but every now and then people will find somewhere that has an archived copy of something pointing to the old domain.

I can publish a new minor version of every library to fix the npm page at least, but it won't help the older versions, since npm doesn't allow overwriting packages.

**Comment by danielo515** [comment]
Oh that makes sense.
Well, at least publishing a minor release will avoid that link to be on the main page of NPM. 
Have you tried to contact npm team? They may offer you an alternative
